stages:
  - test
  - build

test:
  image: gcc
  before_script:
      - cd c-fractals/ 
  stage: test
  script:
    - make test
    
build:
  image: gcc
  before_script:
      - cd c-fractals/ 
  stage: build
  script: 
    - make library
    - cp libfractal.dll libfractal_Linux.dll
    - cp libfractal.dll libfractal.so
  artifacts:
    paths:
      - c-fractals/libfractal_Linux.dll
      - c-fractals/libfractal.so
