stages:
  - test
  - build
  - dist

test:
  image: gcc
  before_script:
      - cd c-fractals/ 
  stage: test
  script:
    - make test
    
build:
  image: gcc
  before_script:
      - cd c-fractals/ 
  stage: build
  script: 
    - make library
    - mv libfractal.dll libfractal_Linux.dll
  artifacts:
    paths:
      - c-fractals/libfractal_Linux.dll

build_gui:
  tags:
    - shared-windows
    - windows
  stage: dist
  before_script:
    - choco install python --version=3.7.9 -y
    - choco install mingw -y
    - refreshenv
  script:
    - C:/Python38/python.exe --version
    - C:/Python38/Scripts/pip.exe install PyQt5
    - C:/Python38/Scripts/pip.exe install pyinstaller
    
    - powershell -File build-win.ps1
  artifacts:
    paths:
      - c-fractals/libfractal_Windows.dll
      - python-fractals/PyFractals.zip
