image: gcc

build:
  before_script:
      - cd c-fractals/ 
  stage: build
  script: make build
  artifacts:
    paths:
      - a_release.exe

test:
  before_script:
      - cd c-fractals/ 
  stage: test
  script:
    - make test