stages:
  - test
  - build
  - dist

test:
  image: gcc
  before_script:
      - cd c-fractals/ 
  stage: test
  script:
    - make test
    
build:
  image: gcc
  before_script:
      - cd c-fractals/ 
  stage: build
  script: make build
  artifacts:
    paths:
      - a_release.exe

build_gui:
  tags:
    - shared-windows
    - windows
  stage: dist
  before_script:
    - cd python-fractals/
    - choco install python --version=3.8.3 -y
    - refreshenv
  script:
    - C:/Python38/python.exe --version
    - C:/Python38/Scripts/pip.exe install PyQt5
    - C:/Python38/Scripts/pip.exe install pyinstaller
    - powershell -File build-win.ps1
  artifacts:
    paths:
      - python-fractals/PyFractals.zip
