name: build

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install gcovr
      run: |
        sudo apt -y install gcovr
    - name: Test
      run: |
        gcc --version
        cd c-fractals
        make test
    - uses: codecov/codecov-action@v2

  build_ubuntu:
    strategy:
      matrix:
        tag: [focal]
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Build c-fractals
      run: |
        gcc --version
        cd c-fractals
        make library
        cp libfractal.so ../libfractal.so
        cd ..
    - name: Install cuda
      run: |
        sudo apt -y install nvidia-cuda-toolkit
        nvcc --version
    - name: Build cuda-fractals
      run: |
        cd cuda-fractals
        make lib
        cp libcudafractals.so ../libcudafractals.so
        cd ..
    - name: Get raylib library
      run: |
        curl -o raylib.tar.gz -L https://github.com/raysan5/raylib/releases/download/3.7.0/raylib-3.7.0_linux_amd64.tar.gz
        tar -xf raylib.tar.gz
        cp raylib-*_linux_amd64/lib/libraylib.a libraylib.a
    - name: Build raylib-cuda
      run: |
        cd raylib-fractals
        make build-cuda
        cp a_release.exe ../run_raylib_cuda
        cd ..
    - name: Build raylib-normal
      run: |
        cd raylib-fractals
        make clean
        make build
        cp a_release.exe ../run_raylib
        cd ..
    - name: Upload libfractal.so
      uses: actions/upload-artifact@v2
      with:
        name: libfractal.so
        path: libfractal.so
    - name: Upload libcudafractals.so
      uses: actions/upload-artifact@v2
      with:
        name: libcudafractals.so
        path: libcudafractals.so
    - name: Upload run_raylib_cuda
      uses: actions/upload-artifact@v2
      with:
        name: run_raylib_cuda
        path: run_raylib_cuda
    - name: Upload run_raylib
      uses: actions/upload-artifact@v2
      with:
        name: run_raylib
        path: run_raylib

  release:
    runs-on: ubuntu-latest
    needs: [build_ubuntu]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          libfractal.so
          libcudafractals.so
          run_raylib
          run_raylib_cuda