name: docs

on:
  push:
    branches: [ master ]]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.3.1
      with:
        doxyfile-path: "docs/Doxyfile"
        working-directory: "c-fractals"
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: c-fractals/docs/html
